/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brandon Westlake (https://sketchfab.com/dr.badass2142)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/retro-computer-setup-free-82eaf2047e0447a1bfea22482f1d1404
Title: Retro Computer Setup (FREE)
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import ComputerScene from '../assets/3d/computer.glb'

const Computer = (props) => {
  const islandRef = useRef();
  const { nodes, materials } = useGLTF(ComputerScene);
  return (
    <a.group ref={islandRef} {...props}>
      <mesh
        geometry={
          nodes.retro_computer_setup_retro_computer_setup_Mat_0.geometry
        }
        material={materials.retro_computer_setup_Mat}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  );
};


export default Computer;
